name: CI
on:
  push:
    branches: main
    paths:
    - .github/workflows/*.y*ml
    - '**.rb'
  pull_request:
    paths:
    - .github/workflows/*.y*ml
    - '**.rb'
  schedule:
  - cron: 0 5 * * *

jobs:
  CI:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-11, macOS-12]

    steps:
    - name: Set up Keychain Access
      run: >
        security add-generic-password -T /usr/bin/security
        -a $USER -s mixed-in-key -w ${{secrets.HOMEBREW_MIXED_IN_KEY_VIP_CODE}}

    - name: ${{github.workflow}}
      uses: danielbayley/homebrew-pipeline@main
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
